apiVersion: v1
kind: ConfigMap
metadata:
  name: dhos-reporting-api-cm
  labels:
    app: dhos-reporting-api
data:
  DATABASE_HOST: {{ .Values.database.host }}
  DATABASE_USER: {{ .Values.database.user_name }}
  DATABASE_NAME: {{ .Values.database.name }}
  DATABASE_PORT: "5432"
  DATABASE_SU_USER: {{ .Values.database.su_name }}
  ALLOW_DROP_DATA: "{{.Values.allow_drop_data}}"
  ENVIRONMENT: {{ .Values.environment }}
  LOG_LEVEL: {{ .Values.log_level | default "INFO" }}
