apiVersion: v1
kind: Secret
metadata:
  name: dhos-reporting-api-secrets
  labels:
    app: dhos-reporting-api
data:
  DATABASE_PASSWORD: "{{ .Values.database.user_password | b64enc }}"
  DATABASE_SU_PASSWORD: "{{ .Values.database.su_password | b64enc }}"
