database:
  host: uk-dev-api-upstream-quail-db.postgres.database.azure.com
  user_name: dhos-reporting@uk-dev-api-upstream-quail-db
  su_name: postgres@uk-dev-api-upstream-quail-db
  name: dhos-reporting

environment: DEVELOPMENT
imagePullPolicy: Always
# This placeholder value gets overridden by devops-release-config during a release
imagetag: dev
allow_drop_data: true
host_env: azure
log_level: DEBUG

gateway_url: https://api-uk-dev.sensynehealth.com

ingress:
  hostName: api-dev.sensynehealth.local
