database:
  host: us-prod-upstream-api001-oriole-db.postgres.database.azure.com
  user_name: dhos-reporting@us-prod-upstream-api001-oriole-db
  su_name: postgres@us-prod-upstream-api001-oriole-db
  name: dhos-reporting

environment: PRODUCTION
imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config-prod during a release
imagetag: r1.14.0
allow_drop_data: false
host_env: azure

gateway_url: https://api-us-prod.sensynehealth.com

ingress:
  hostName: api-prod.sensynehealth.local
