database:
    user_password: ENC[AES256_GCM,data:d4AfqGxXbbcqPipt9vP9DL67Tg/Kw9yrwl5R2A9nwJs=,iv:y4ORYVjAzluLqsH49TMF3+WdKTbmrBIpKnDXVoBqe88=,tag:iQJ6wuImYbD8ycts4OWlTg==,type:str]
    su_password: ENC[AES256_GCM,data:5XLP5Amo08X3Q/P5arXvUyCB+4PIb7vFFbczXMaeuiI=,iv:n97oc0U0Ig/zxN9Y+IGhJaPBE5rGHtajOk7ih0ps29Q=,tag:S/fmlxie0qx4csyOvym2Dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://us-nonprod-keyvault.vault.azure.net
          name: dhos-reporting-api-sops
          version: ec6a6cc2a8ed468ba74a1afdf17b7849
          created_at: "2022-04-20T09:53:38Z"
          enc: JsZi-wVCGg0TKervg9SrvA-FJqsMiqk-sz2agOTd4P6zfEMEwQUvmwebzbGkVBQMRajXDeAHKytV90PjoNR8XA7ZVLWuAE-zNZgjs9IhlTW50YZO3MZU8n9kbYJTW9ca8zE45aNRZsWlus5cKOfQZLlz3Psw51faUvHf4ZfJegOyK67CknSTf3Nk4ifKsP5QXsRC8RufLcL4-qrI2beyGrJDvaoAZdUeuO00ZJJMGW-DQrf0DS3Jb8x3vTQBI0MgvknzAeCzrZxQIxlesJ0LzfoYajHDsnbqo7f8txOuIHuS3slAv9V0GIiolYKQnENl59sniWl6wFsSqduP7OTv4A
    hc_vault: []
    age: []
    lastmodified: "2022-04-20T09:53:40Z"
    mac: ENC[AES256_GCM,data:FK+/zBLbOYeKPGZfAOs2syBHt1AA63pwFxujRDuuERdrlwd9JOdGijRBl3B9d4O5QSluEWJPGyj1tO54DWx2a49w8bkkRU08MECWcSHRr1pkU+UlkqkVhpyMhLbCC4n/vgPF0UjuKoYn0EUWcJdoVCZzI/qlv0SXKIK2cRiO/zM=,iv:8TeADD44gild+ZA0BAadfqctQqbvUKJTujdmOwILBuc=,tag:XyfwStQ4U7ikPudqFhrzNQ==,type:str]
    pgp:
        - created_at: "2022-04-20T09:53:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQf/cSPHYCRTB8vTHw5xA8HIt9m8VqYfNlfRFz4tuk44z/oo
            Uu3iWJsKq7cGJw9xxTGggTYbmz0Dczy5nvcSbI444zpeGIM8z6bsJcRJlA7Nbk1s
            8O22qvJLl0ZOxxcz40rUj/qSpSpjYmmgRz0n16k4llcN/fjwKi81kNf5wb6Whstn
            LCFxo8UjAlqyci2EbqSGxOx7/D/3txHIB45PJ6leYckZPZHJHUGRt+iVCz51MduN
            j7GoHN07tNkyhqJgSR2qhQh8CVilgiVaFOZHC9GgNB3QVy1OKxLWInY9OX+NYrrJ
            atA7mKZhrwrSjuheQhcEsCUsYPzlLDg2CUVn8gjprNJeAfrq2qPjG+Wmf3G3Qskr
            lE47L6OofF7Z23QULZApzb50Yhzks7ewFTfKgYWOAMztaeMNELFKM/HhzKpLGsDJ
            Afs3FP177CSYXM5pMJVQYs84bo9d0n2YYgjcv3Pu7A==
            =ss16
            -----END PGP MESSAGE-----
          fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.7.2
