database:
    user_password: ENC[AES256_GCM,data:vtteHVPqYbmcfq6MZQG2nwuHewZ5Qc93bPNtXhd0Ppc=,iv:70qeM/bIpGBZRhaphURnn/411LahL5XSPvsEQbdYHzk=,tag:iBDcitDOYSBnqRa98QkoNw==,type:str]
    su_password: ENC[AES256_GCM,data:vNS6zUI4aDU9gUTfVJPsDT/yCC41Qrzl4hUNRwQ9s58=,iv:BlRTxbkc1C21Snxi8S2JxqrmlwFhfYgAXq0GMjE7kIQ=,tag:LNFZv8LGCbrnRsdzN9M+GA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://uk-nonprod-keyvault.vault.azure.net
          name: dhos-reporting-api-sops
          version: d21cfae95e5943d1ae7e79b6e7447da6
          created_at: "2022-04-20T09:53:23Z"
          enc: YV9E9AQFsfMr0VK34T05rXyrLYOW6W82R5KzxM0ofG_3wlEQxbYdpUO27NZMPA6Ne6i2-bQR_DN63chu4bqwR77efe4NVLA_E8KGGq5Q1Dovz2xIKH6uwDH8qNbjc9I0OIt8VmjjbnGXj8StJi7r9r8nCvcuI5f5ubtioT8bkvSKmGmuC_ZwkXYZSP5Ynr_2Qd-YI7CjdxTXb6Y3TqHxM6G8eGc9QkYviQ7hxdVogXFFeQx0hELcA87k000tQjnotQC2sxZR9bxKxt-C28INmnuHmwjVGthDTrUHMz10hDdQjJ8U2CMDMwx6tniBBW4VrcPHqU3ybLOxwsW9xL_sAg
    hc_vault: []
    age: []
    lastmodified: "2022-05-12T10:20:49Z"
    mac: ENC[AES256_GCM,data:hKXJyAkdJbSfkXf6nXa7q04LMrqrZiQL0BP/OAJCGQwjumaA9A3fHYOUPQXzwnLql/ucQmWpK5l3F4p6dL1MdG2X8kNIOEWGGCMhp/g61wBRvDy4F3Bmlnkfzrt2iF5zcbenl7P8IWAbzW46p9XsaqCZrXfH4UeTMHu3x2HgOJk=,iv:j+3TC+fC6w6m1+VFduqzZTSc7Mp+kyc6XqeevOLWx+g=,tag:fol1nNdqPPbGroxKxSaCaw==,type:str]
    pgp:
        - created_at: "2022-04-20T09:53:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQf/QpIiXsPxIuj4fSR65eLouWz7khpq9JRwLgf/sBm0by6/
            ijiehx4PnSTvLADzr8g0CIRatkXP28AqyRLJ0rm6+8qLmrDqgvyY1NxJEgGPF+HV
            8G1MmSoTpXFGcsz+unJT4ec6XIN6SRr5061wbN8FasUS10B3QISVJWr3G0QW2Uq2
            OTocvYZdLhTsEo6QWty/2KPw/12GBc52aZsmx6GjEejVFBpq4SV9WYPxD9fQVdOO
            WOLlXWlXa97HUHgJmGwf4ZDOn0xj+uPu2aUv1kWhAsJfJ8Mrg0EbFIqYxc3hM4eq
            KQG6Jfo2h2TPcfM/UIOXbu0L2GvTAjNFHsSd6w0OW9JcAaNszt5KqMZeAl6TS+k+
            X7EYAJ0q1d/HAtL11fs6sDDF//B04f9eoW/ou6RQIgpqYPlf1K1b8HgvDxtIk+Ax
            taUXdtg8dXkftGQ0bX3AbYYAZn3bRc2qyP29398=
            =7+g3
            -----END PGP MESSAGE-----
          fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.7.2
