database:
    user_password: ENC[AES256_GCM,data:LGmZ/4RCqQU25gZjqIgjvOf+sAjWlsi66/kn8qQH8v8=,iv:Ezy22mQy5+Nb+QgDtolOXC9AwtORR+ArUDoYkLRf9fI=,tag:uR8/aGJ57tuuvHZKlFdJ8Q==,type:str]
    su_password: ENC[AES256_GCM,data:zBw3XYFs6w54WKExj7aTEj4RH1I9Vi2dALdTlKp7T8U=,iv:hAJ/ygiDiMJxvu6MCBy6Qq/sJgTmFZ1BOb4QasZDkOk=,tag:ha18Lzp4EOrIcNxuyZwy/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sh-us-dev-keyvault.vault.azure.net
          name: dhos-reporting-api-sops
          version: f127bd11b91843f6896f5e48c05ab6b8
          created_at: "2022-04-20T09:53:54Z"
          enc: PpPFeEEiHDtHTC88uV25GTBrlnBhuHXXeqLDkmgD1fI0I8f7BxOycrAxMjUHnvJUmTttulFJdCir4oi66cf69Ow6PMri9t9wt-pjJDjdyZ0ZWYz2VYlp3L96W2fEwF2Elrz8HzbML1Lq2DWHGzGPj6g3kTpQih8W6OwV6mtec8ZmuvWpKw2XKynY3gJZt0QFB_4fK1WdGAng5Kii_q-uLeR5fn3tOZIGrNNf580JcNLRN5YYO3XjcQjN1qeQaSqyVBhB6UiyhEZbuQWhUqmfVKBrZIpMjz6Q4lLP_rO4LIB9tfNZdxXT-rEW5RuazPtWKn5HVGIj1DCfKGrObHiQnw
    hc_vault: []
    age: []
    lastmodified: "2022-04-20T09:53:56Z"
    mac: ENC[AES256_GCM,data:Fx3ZDfTuw1o1QCz5BHMMZHoCZ3tkimCIGM+h5rskkHgh74rWmAq5H452NYC8WxHdNpABgozEQaba2xoF0sGzVnes9fwqy8qUn4bKNe/aobRN4n+j/WjWnvgOloIbxFECLZFD4dVfT97ZZUjUvpZ0vJqE2H8s3LPLsK9iL/ZuzUc=,iv:vguqgHN2/U3GJfkMhsWKJne8NrqvS0lKYgKbAjjDQqA=,tag:wsh1VAz6T4j0NkPao+CGAw==,type:str]
    pgp:
        - created_at: "2022-04-20T09:53:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6zMWHGWY4fTAQgAjLx+C5Nz18boE+APgf1X2BFpKe1/uBJebfO649RYxhYe
            lnFGaNAah/UsD/rxo9mSDFbqVA6xrpCJ+yNn06mJmp8/uKs4+RcEKRrMxx8Z2lE+
            czYQ6gecK6KygIl7pWlECrysrfQCBSsb3oeRu+0Zm8wxqvipeSUgd2DJBJpk90vC
            4xXAV6QR6XGi119Y62aiXjAOqzizTtm0tYs0Qb3UQQOfNYxDXh2PpgheJbbLzEoJ
            t8j0yzFOXgP5qdyo7tffEKvqjuDrDeNAyRIvSrZ04PMFISvJoXz9ZPWQYSX9UMJh
            wVECLZPP3zNoe86TVZUD8WZ+UHOnj/B0QGgLYh2gqdJeAYy4TobDBP9dpFq2rMBT
            AbjiRgT+un2O1ut6R1AcWKYbuIpcCHeuNZztJwPCXCyyPN7hYlW5IfvcsKIx9oQo
            EaklYTceMMdtKzBLl6PR5Fvt+TAKAzU7ziWgOI1pJw==
            =5jgd
            -----END PGP MESSAGE-----
          fp: 8872B8F99E83960708A51F9BA6B64CBF0636EFDA
    unencrypted_suffix: _unencrypted
    version: 3.7.2
