database:
  host: uk-prod006-hog-db.postgres.database.azure.com
  user_name: dhos-reporting@uk-prod006-hog-db
  su_name: postgres@uk-prod006-hog-db
  name: dhos-reporting

environment: PRODUCTION
imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config-prod during a release
imagetag: r1.14.0
allow_drop_data: false
host_env: azure

gateway_url: https://api-uk-prod.sensynehealth.com

ingress:
  hostName: api-prod.sensynehealth.local
