database:
  host: uk-nonprod-upstream-api001-shepherd-db.postgres.database.azure.com
  user_name: dhos-reporting@uk-nonprod-upstream-api001-shepherd-db
  su_name: postgres@uk-nonprod-upstream-api001-shepherd-db
  name: dhos-reporting

environment: NONPRODUCTION
imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config during a release
imagetag: r1.14.0
allow_drop_data: false
host_env: azure

gateway_url: https://api-uk-nonprod.sensynehealth.com

ingress:
  hostName: api-nonprod.sensynehealth.local
